backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Category / Tag", name: "tag", widget: "select", options: ["Contractor Tips", "Risk Assessment", "DIY Security", "Industry Insights", "Security Brief", "News"] }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image (optional)", name: "image", widget: "image", required: false }
